### ISSUE TITLE
Release SDK 0.1.0

### ISSUE THREAD

**Issue by bitbeckers** [hypercerts-org/hypercerts#681]
### Describe the feature you'd like to request

Release the updated SDK 0.1.0 which introduces breaking changes

### Describe the solution you'd like

Checklist:

- [x] #776
- [x] #773
- [x] Allow tx override #533 
- [x] Rename SDK package #676 
- [x] Add Winston console logging or remove from SDK: #600 
- [x] Release to NPM
- [ ] Verify fix for #505 
- [ ] Review #306 

### Describe alternatives you've considered

This is the gwei

**Comment by ryscheng** [comment]
Might be a good point to do package renaming at this point, thanks Ken!
https://github.com/hypercerts-org/hypercerts/issues/676

**Comment by bitbeckers** [comment]
> - [ ] Verify fix for #505 
> - [ ] Review #306

Reached out and tracking there in favor of closing this one.
