### ISSUE TITLE
EPIC: Fund impact by ‘shopping’ in registry

### ISSUE THREAD

**Issue by benedictvscriticus** [hypercerts-org/hypercerts#983]
- [ ] STORY: As a funder, I want to be able to select an available Hypercert from a web shop-like interface and mint it by going through a cart-based checkout process.
    - [ ] TASK: Design checkout flow using Chakra components or similar
    - [ ] TASK: Research and define architecture for Hypercerts issuance via the registry
    - [ ] FEAT: Hypercerts are bought by funders from the registry.
    - [ ] FEAT: Hyperboards only display the aggregate amount of all Hypercert-blueprints that are still available in a given category.
    - [ ] Fractions of the Hypercerts are sent from the organisers to the funders.
    - [ ] QUEST: Are mutations subject to an owner signature and admin approval?
    - [ ] FEAT: An empty hyperboard is a registry of hypercert-blueprints.
    - [ ] FEAT: Sponsoring a fraction of a hypercert representing organizers (future) work, returns the funder with a Hypercert for their sponsorship.
    - [ ] TASK: Research mutable metadata implementation according to the following scenarios
        - Creator can propose change
        - For now: HF can approve change
        - Later: Decentralize approval
- [ ] STORY: As a funder, I want to be able to provide all metadata that is included in the Hypercert upon checkout.
    - [ ] TASK: Research how to display a Hypercert owners.
    - [ ] TASK: Define how Hypercert owner with 0x address, and ‘display name’, a given logo, and a description are displayed. in a specific way.
    - [ ] FEAT: Metadata is stored in a centralised database.
    - [ ] TASK: Uploaded images should be stored in a centralised database.
- [ ] STORY: As a super admin, I want to be able to control the cost of Hypercerts for it to correlate with the display size on a Hyperboard.
- [ ] STORY: As an owner, I want to be able to choose which logo is displayed on the Hypercert.
     - [ ] FEAT: Owners are prompted to give a display name, which may be displayed on the Hypercert.
- [ ] As a super admin, I want to have superseding rights over all actors for a specific Hyperboard or sets thereof.
