### ISSUE TITLE
EPIC: 4 - Registry administration panel

### ISSUE THREAD

**Issue by benedictvscriticus** [hypercerts-org/hypercerts#986]
- [ ] #1040
    - [ ] #990
    - [ ] #1044
    - [ ] FEAT: We do not assume they are legal persons.
    - [ ] #1043
- [ ] #1042
    - [ ] FEAT: Sign in with Ethereum
    - [ ] TASK: Add “Create registry form”, allow for whitelisting organizer addresses
    - [ ] TASK: Add “Create Hypercert blueprint” form, allow organizers to create blueprints.
    - [x] #1036
    - [ ] TASK: Add list view for hypercert-blueprints for organizers
    - [ ] TASK: Add detail view for Hypercert-blueprints
    - [ ] TASK: Add delete Hypercert-blueprint functionality
    - [x] #1041
    - [ ] FEAT: We should use Plasmic as a wrapper for our custom code components
    - [ ] FEAT: Sponsorship will be a separate website and separate entity. It will provide a central place where you can do this.
    - [ ] TASK: Set up a project in Plasmic.
    - [ ] TASK: Set up a project for Vercel.
    - [ ] TASK: Decide on technology stack
    - [ ] TASK: Add form to allow creating multiple related hypercert-blueprints
